=== HealthCatalyst/dos.install/deployments/schema.json
{
    "$id": "http://example.com/example.json",
    "type": "object",
    "definitions": {},
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "kubectl": {
            "$id": "/properties/kubectl",
            "type": "object",
            "properties": {
                "version": {
                    "$id": "/properties/kubectl/properties/version",
                    "type": "string",
                    "title": "Version of kubectl to install locally",
                    "default": "",
                    "examples": [
                        ""
                    ]
                }
            }
        },
        "kubernetes": {
            "$id": "/properties/kubernetes",
            "type": "object",
            "properties": {
                "version": {
                    "$id": "/properties/kubernetes/properties/version",
                    "type": "string",
                    "title": "Version of kubernetes server to install in Azure",
                    "default": "",
                    "examples": [
                        ""
                    ]
                }
            }
        },        
        "azcli": {
            "$id": "/properties/azcli",
            "type": "object",
            "properties": {
                "version": {
                    "$id": "/properties/azcli/properties/version",
                    "type": "string",
                    "title": "The Version Schema ",
                    "default": "",
                    "examples": [
                        "2.0.27"
                    ]
                }
            }
        },
        "azure": {
            "$id": "/properties/azure",
            "type": "object",
            "properties": {
                "resourceGroup": {
                    "$id": "/properties/azure/properties/resourceGroup",
                    "type": "string",
                    "title": "Resourcegroup",
                    "default": "",
                    "examples": [
                        "Prod-Kub-HCUT-RG"
                    ]
                },
                "location": {
                    "$id": "/properties/azure/properties/location",
                    "type": "string",
                    "title": "Location",
                    "default": "",
                    "examples": [
                        "westus"
                    ]
                },
                "create_windows_containers": {
                    "$id": "/properties/azure/properties/create_windows_containers",
                    "type": "boolean",
                    "title": "The Create_windows_containers Schema ",
                    "default": false,
                    "examples": [
                        false
                    ]
                },
                "use_azure_networking": {
                    "$id": "/properties/azure/properties/use_azure_networking",
                    "type": "boolean",
                    "title": "The Use_azure_networking Schema ",
                    "default": false,
                    "examples": [
                        true
                    ]
                },
                "acs_engine": {
                    "$id": "/properties/azure/properties/acs_engine",
                    "type": "object",
                    "properties": {
                        "version": {
                            "$id": "/properties/azure/properties/acs_engine/properties/version",
                            "type": "string",
                            "title": "The Version Schema ",
                            "default": "",
                            "examples": [
                                "v0.13.0"
                            ]
                        }
                    }
                },
                "masterVMSize": {
                    "$id": "/properties/azure/properties/masterVMSize",
                    "type": "string",
                    "title": "masterVMSize",
                    "default": "Standard_DS2_v2",
                    "examples": [
                        "Standard_DS2_v2"
                    ]
                },
                "workerVMSize": {
                    "$id": "/properties/azure/properties/workerVMSize",
                    "type": "string",
                    "title": "workerVMSize",
                    "default": "Standard_DS2_v2",
                    "examples": [
                        "Standard_DS2_v2"
                    ]
                }                                
            }
        },
        "service_principal": {
            "$id": "/properties/service_principal",
            "type": "object",
            "properties": {
                "name": {
                    "$id": "/properties/service_principal/properties/name",
                    "type": "string",
                    "title": "The Name Schema ",
                    "default": "",
                    "examples": [
                        ""
                    ]
                },
                "delete_if_exists": {
                    "$id": "/properties/service_principal/properties/delete_if_exists",
                    "type": "boolean",
                    "title": "The Delete_if_exists Schema ",
                    "default": false,
                    "examples": [
                        true
                    ]
                }
            }
        },
        "storage_account": {
            "$id": "/properties/storage_account",
            "type": "object",
            "properties": {
                "delete_if_exists": {
                    "$id": "/properties/storage_account/properties/delete_if_exists",
                    "type": "boolean",
                    "title": "The Delete_if_exists Schema ",
                    "default": false,
                    "examples": [
                        false
                    ]
                }
            }
        },
        "local_folder": {
            "$id": "/properties/local_folder",
            "type": "string",
            "title": "The Local_folder Schema ",
            "default": "",
            "examples": [
                "c:\\kubernetes"
            ]
        },
        "customerid": {
            "$id": "/properties/customerid",
            "type": "string",
            "title": "The Customerid Schema ",
            "default": "",
            "examples": [
                "hcut"
            ]
        },
        "ssl": {
            "$id": "/properties/ssl",
            "type": "boolean",
            "title": "The Ssl Schema ",
            "default": false,
            "examples": [
                false
            ]
        },
        "ssl_folder": {
            "$id": "/properties/ssl_folder",
            "type": "string",
            "title": "Read SSL keys from this folder",
            "default": "",
            "examples": [
                "c:\\kubernetes"
            ]
        },
        "allow_kubectl_from_outside_vnet": {
            "$id": "/properties/allow_kubectl_from_outside_vnet",
            "type": "boolean",
            "title": "The Allow_kubectl_from_outside_vnet Schema ",
            "default": false,
            "examples": [
                false
            ]
        },
        "ingress": {
            "$id": "/properties/ingress",
            "type": "object",
            "properties": {
                "external": {
                    "$id": "/properties/ingress/properties/external",
                    "type": "string",
                    "enum": ["public", "onprem", "whitelist", "vnetonly"],
                    "title": "The External Schema ",
                    "default": "",
                    "examples": [
                        "public"
                    ]
                },
                "internal": {
                    "$id": "/properties/ingress/properties/internal",
                    "type": "string",
                    "enum": ["public", "onprem", "vnetonly"],
                    "title": "The Internal Schema ",
                    "default": "",
                    "examples": [
                        "private"
                    ]
                },
                "external_ip_whitelist": {
                    "$id": "/properties/ingress/properties/external_ip_whitelist",
                    "type": "string",
                    "title": "Provide an address range using CIDR notation (e.g. 192.168.99.0/24); an IP address (e.g. 192.168.99.0); or a list of address ranges or IP addresses (e.g. 192.168.99.0/24,10.0.0.0/24,44.66.0.0/24).",
                    "default": "",
                    "examples": [
                        ""
                    ]
                },
                "fixloadbalancer": {
                    "$id": "/properties/fixloadbalancer",
                    "type": "boolean",
                    "title": "Whether to fix the load balancer",
                    "default": true,
                    "examples": [
                        false
                    ]
                }
            }
        },
        "networking": {
            "$id": "/properties/networking",
            "type": "object",
            "properties": {
                "vnet": {
                    "$id": "/properties/networking/properties/vnet",
                    "type": "string",
                    "title": "The Vnet Schema ",
                    "default": "",
                    "examples": [
                        "CAPVnet"
                    ]
                },
                "subnet": {
                    "$id": "/properties/networking/properties/subnet",
                    "type": "string",
                    "title": "The Subnet Schema ",
                    "default": "",
                    "examples": [
                        "HCUT"
                    ]
                },
                "subnet_resource_group": {
                    "$id": "/properties/networking/properties/subnet_resource_group",
                    "type": "string",
                    "title": "The Subnet_resource_group Schema ",
                    "default": "",
                    "examples": [
                        "capresourcegroup"
                    ]
                }
            }
        },
        "network_security_group": {
            "$id": "/properties/network_security_group",
            "type": "object",
            "properties": {
                "name": {
                    "$id": "/properties/network_security_group/properties/name",
                    "type": "string",
                    "title": "The Name Schema ",
                    "default": "",
                    "examples": [
                        ""
                    ]
                },
                "create_nsg_rules": {
                    "$id": "/properties/network_security_group/properties/create_nsg_rules",
                    "type": "boolean",
                    "title": "The Create_nsg_rules Schema ",
                    "default": false,
                    "examples": [
                        true
                    ]
                }
            }
        },
        "dns": {
            "$id": "/properties/dns",
            "type": "object",
            "properties": {
                "name": {
                    "$id": "/properties/dns/properties/name",
                    "type": "string",
                    "title": "The Name Schema ",
                    "default": "",
                    "examples": [
                        "hcut.healthcatalyst.net"
                    ]
                },
                "create_dns_entries": {
                    "$id": "/properties/dns/properties/create_dns_entries",
                    "type": "boolean",
                    "title": "The Create_dns_entries Schema ",
                    "default": false,
                    "examples": [
                        false
                    ]
                },
                "dns_resource_group": {
                    "$id": "/properties/dns/properties/dns_resource_group",
                    "type": "string",
                    "title": "The Dns_resource_group Schema ",
                    "default": "",
                    "examples": [
                        "dns"
                    ]
                }
            }
        }
    }
}

=== HealthCatalyst/dos.install/deployments/fabrickubernetes.json
{
    "$schema": "https://raw.githubusercontent.com/HealthCatalyst/dos.install/master/deployments/schema.json",
    "kubectl": {
        "version": "1.10.0"
    },
    "kubernetes": {
        "version": "1.10.0"
    },    
    "azcli": {
        "version": "2.0.30"
    },
    "azure": {
        "subscription": "Health Catalyst - Fabric",
        "resourceGroup": "fabrickubernetes",
        "location": "eastus",
        "create_windows_containers": false,
        "use_azure_networking": true,
        "acs_engine": {
            "version": "0.15.0"
        },
        "masterVMSize": "Standard_DS2_v2",
        "workerVMSize": "Standard_DS2_v2"
    },
    "service_principal": {
        "name": "",
        "delete_if_exists": true
    },
    "storage_account": {
        "delete_if_exists": false
    },
    "local_folder": "c:\\kubernetes",
    "customerid": "hcut",
    "ssl": false,
    "allow_kubectl_from_outside_vnet": true,
    "ingress": {
        "external": "public",
        "internal": "public",
        "external_ip_whitelist": "",
        "fixloadbalancer": false
    },
    "networking": {
        "vnet": "kubnettest",
        "subnet": "kubsubnet",
        "subnet_resource_group": "Imran"
    },
    "network_security_group": {
        "name": "",
        "create_nsg_rules": false
    },
    "dns": {
        "name": "fabrickubernetes.eastus.cloudapp.azure.com",
        "create_dns_entries": false,
        "dns_resource_group": "dns"
    }
}

=== HealthCatalyst/dos.install/deployments/prod-kub-sjtn.json
{
    "$schema": "https://raw.githubusercontent.com/HealthCatalyst/dos.install/master/deployments/schema.json",
    "kubectl": {
        "version": "1.10.0"
    },
    "kubernetes": {
        "version": "1.10.0"
    },    
    "azcli": {
        "version": "2.0.30"
    },
    "azure": {
        "resourceGroup": "Prod-Kub-SJTN-RG",
        "location": "westus",
        "create_windows_containers": false,
        "use_azure_networking": true,
        "acs_engine": {
            "version": "0.15.0"
        },
        "masterVMSize": "Standard_DS2_v2",
        "workerVMSize": "Standard_DS2_v2"
    },
    "service_principal": {
        "name": "",
        "delete_if_exists": false
    },
    "storage_account": {
        "delete_if_exists": false
    },
    "local_folder": "c:\\kubernetes",
    "customerid": "sjtn",
    "ssl": true,
    "ssl_folder": "c:\\kubernetes\\certs\\sjtn",        
    "allow_kubectl_from_outside_vnet": false,
    "ingress": {
        "external": "whitelist",
        "internal": "vnetonly",
        "external_ip_whitelist": "40.70.58.54,192.55.208.0/24"
    },
    "networking": {
        "vnet": "CAPVnet",
        "subnet": "SJTN",
        "subnet_resource_group": "capresourcegroup"
    },
    "network_security_group": {
        "name": "",
        "create_nsg_rules": true
    },
    "dns": {
        "name": "sjtn.healthcatalyst.net",
        "create_dns_entries": false,
        "dns_resource_group": "dns"
    }
}

=== HealthCatalyst/dos.install/deployments/devkubernetes.json
{
    "$schema": "https://raw.githubusercontent.com/HealthCatalyst/dos.install/master/deployments/schema.json",
    "kubectl": {
        "version": "1.10.0"
    },
    "kubernetes": {
        "version": "1.10.0"
    },    
    "azcli": {
        "version": "2.0.30"
    },
    "azure": {
        "resourceGroup": "devkubernetes",
        "location": "westus",
        "create_windows_containers": false,
        "use_azure_networking": true,
        "acs_engine": {
            "version": "0.15.0"
        },
        "masterVMSize": "Standard_DS2_v2",
        "workerVMSize": "Standard_DS2_v2"
    },
    "service_principal": {
        "name": "",
        "delete_if_exists": true
    },
    "storage_account": {
        "delete_if_exists": false
    },
    "local_folder": "c:\\kubernetes",
    "customerid": "hcut",
    "ssl": false,
    "allow_kubectl_from_outside_vnet": false,
    "ingress": {
        "external": "vnetonly",
        "internal": "vnetonly",
        "external_ip_whitelist": ""
    },
    "networking": {
        "vnet": "DevKubernetes",
        "subnet": "default",
        "subnet_resource_group": "DevKubernetes"
    },
    "network_security_group": {
        "name": "",
        "create_nsg_rules": true
    },
    "dns": {
        "name": "devkubernetes.hqcatalyst.local",
        "create_dns_entries": false,
        "dns_resource_group": "dns"
    }
}

=== HealthCatalyst/dos.install/deployments/prod-kub-ahmn.json
{
    "$schema": "https://raw.githubusercontent.com/HealthCatalyst/dos.install/master/deployments/schema.json",
    "kubectl": {
        "version": "1.10.0"
    },
    "azcli": {
        "version": "2.0.27"
    },
    "azure": {
        "resourceGroup": "Prod-Kub-AHMN-RG",
        "location": "westus",
        "create_windows_containers": false,
        "use_azure_networking": true,
        "acs_engine": {
            "version": "0.14.6"
        }
    },
    "service_principal": {
        "name": "",
        "delete_if_exists": false
    },
    "storage_account": {
        "delete_if_exists": false
    },
    "local_folder": "c:\\kubernetes",
    "customerid": "ahmn",
    "ssl": true,
    "allow_kubectl_from_outside_vnet": false,
    "ingress": {
        "external": "whitelist",
        "internal": "vnetonly",
        "external_ip_whitelist": "64.39.96.0/20"
    },
    "networking": {
        "vnet": "CAPVnet",
        "subnet": "AHMN",
        "subnet_resource_group": "capresourcegroup"
    },
    "network_security_group": {
        "name": "",
        "create_nsg_rules": true
    },
    "dns": {
        "name": "ahmn.healthcatalyst.net",
        "create_dns_entries": false,
        "dns_resource_group": "dns"
    }
}

=== HealthCatalyst/dos.install/deployments/baremetal.json
{
    "$schema": "https://raw.githubusercontent.com/HealthCatalyst/dos.install/master/deployments/schema.json",
    "kubectl": {
        "version": "1.10.0"
    },
    "azcli": {
        "version": "2.0.27"
    },
    "azure": {
        "subscription": "Health Catalyst - Fabric",
        "resourceGroup": "baremetal",
        "location": "eastus",
        "create_windows_containers": false,
        "use_azure_networking": true,
        "acs_engine": {
            "version": "v0.13.0"
        }
    },
    "service_principal": {
        "name": "",
        "delete_if_exists": true
    },
    "storage_account": {
        "delete_if_exists": false
    },
    "local_folder": "c:\\kubernetes",
    "customerid": "hcut",
    "ssl": false,
    "allow_kubectl_from_outside_vnet": true,
    "ingress": {
        "external": "public",
        "internal": "public",
        "external_ip_whitelist": ""
    },
    "networking": {
        "vnet": "baremetal-vnet",
        "subnet": "default",
        "subnet_resource_group": "Imran"
    },
    "network_security_group": {
        "name": "",
        "create_nsg_rules": true
    },
    "dns": {
        "name": "baremetal.healthcatalyst.net",
        "create_dns_entries": false,
        "dns_resource_group": "dns"
    }
}
